Repository ansys/pymaterials-manager, pull requests merged in 2023-04, with the labels that each got.

#76 doc: add version switcher
  doc/source/conf.py
Labels: documentation

#78 DOC - Fix shield URL
  README.rst
Labels: documentation

#79 Ver: Bump version 0.2.dev0
  pyproject.toml
  tests/test_metadata.py
Labels: enhancement, maintenance, testing

#82 ability to write matml as string
  src/ansys/materials/manager/util/matml/matml_from_material.py
  tests/matml/test_matml_from_material.py
Labels: enhancement, testing

#84 bump patch
  pyproject.toml
Labels: maintenance

#87 MAINT - Remove support for python 3.7
  .github/workflows/ci_cd.yml
  README.rst
  poetry.lock
  pyproject.toml
  src/ansys/materials/manager/__init__.py
  tox.ini
Labels: documentation, enhancement, maintenance

#89 CI - Pin poetry pre new installer
  .github/workflows/ci_cd.yml
Labels: maintenance

#90 Minor changes for MATML
  src/ansys/materials/manager/util/matml/matml_from_material.py
  tests/data/ref_steel_eglass_air.xml
Labels: enhancement, testing

#92 don't pass xml_declaration to ElementTree in 3.7
  src/ansys/materials/manager/util/matml/matml_from_material.py
  tests/matml/test_matml_from_material.py
Labels: enhancement, testing

#94 FIX - Fixup class naming and add string_eval property
  tests/fluent/test_serialize_props.py
Labels: maintenance, testing

#95 MAINT - Bump ansys-fluent-core with corresponding mock
  poetry.lock
  pyproject.toml
  tests/fluent/test_serialize_props.py
Labels: dependencies, maintenance, testing
